/// <autosync enabled = "true">
/// <reference path="js/GameMain.js" />
/// <reference path="js/tools.js" />
/// <reference path="libs/threejs/Detector.js" />
/// <reference path="libs/threejs/OrbitControls.js" />
/// <reference path="libs/threejs/SceneLoader.js" />
/// <reference path="libs/threejs/stats.min.js" />
/// <reference path="libs/threejs/three.min.js" />
/// <reference path="libs/Tween.js" />
/// <reference path="libs/tween/Tween.js" />
