/// <autosync enabled = "true">
/// <reference path="game.js" />
/// <reference path="js/base/animation.js" />
/// <reference path="js/base/pool.js" />
/// <reference path="js/base/sprite.js" />
/// <reference path="js/databus.js" />
/// <reference path="js/GameController.js" />
/// <reference path="js/GameMain.js" />
/// <reference path="js/libs/symbol.js" />
/// <reference path="js/libs/threejs/OrbitControls.js" />
/// <reference path="js/libs/threejs/three.min.js" />
/// <reference path="js/libs/Tween.js" />
/// <reference path="js/libs/weapp-adapter.js" />
/// <reference path="js/main.js" />
/// <reference path="js/runtime/background.js" />
/// <reference path="js/runtime/gameinfo.js" />
/// <reference path="js/runtime/music.js" />
